version: '3'
services:

  app:
    build: .
    ports:
     - "${APPLICATION_HTTP_PORT}:8080"
     - "${APPLICATION_GRPC_PORT}:8082"
    volumes:
     - ${APPLICATION}:/go/src/github.com/duhruh/blog
    command: ["go", "run", "cmd/task/main.go", "server", "--watch=true"]
    tty: true
    networks:
      - frontend
      - backend

#  filebeat:
#    build:
#      context: ./docker/filebeat
#      dockerfile: Dockerfile
#    volumes:
#      - ${FILEBEAT_CONFIG}:/usr/share/filebeat/filebeat.yml
#      - ${LOG_PATH}:/mnt/log
#    networks:
#      - backend
#  logstash:
#    image: docker.elastic.co/logstash/logstash:5.6.3
#    networks:
#      - backend

  filebeat:
    build:
      context: ./docker/filebeat
      dockerfile: Dockerfile
    volumes:
     - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
     - ./logs:/mnt/log
     - ./docker/filebeat/filebeat.template.json:/usr/share/filebeat/my.template.json
    tty: true
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - frontend
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-plugins:/usr/share/elasticsearch/plugins
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      - frontend
      - backend

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  mysql:
    driver: "local"
  elasticsearch-data:
    driver: "local"
  elasticsearch-plugins:
    driver: "local"