version: '3'
services:
  app:
    build: .
    ports:
     - "8080:8080"
     - "8082:8082"
    volumes:
     - .:/go/src/github.com/duhruh/blog
    command: ["go", "run", "cmd/task/main.go", "server", "--watch=true"]
