name: blog

version: v0.0.1

description: Blog application

database:
  include>: config/database.yml

http:
  port: 8080

grpc:
  port: 8082

elasticsearch:
  host: "http://elasticsearch:9200"
  username: "elastic"
  password: "changeme"