name: blog

version: v0.0.1

description: Blog application

entry_point: cmd/app/main.go

config_path: github.com/duhruh/blog/config

task_entry_point: cmd/task/main.go

log_path: ./logs/blog.log

database:
  include>: config/database.yml

http:
  port: 8080

grpc:
  port: 8082

#elasticsearch:
#  host: "http://elasticsearch:9200"
#  username: "elastic"
#  password: "changeme"